version: "3.9"

services:
  db:
    image: postgres:16.2-alpine3.18
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - 80:8000
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_PASSWORD=4dm1n.
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    restart: always
